networks:
    vprofile-networks:
        driver: bridge
volumes:
    vprofile-app-data:
        driver: local
    vprofile-db-data:
        driver: local

services:
    vprofile-db:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        image: sramtekkar/vprofile-db
        container_name: vprodb
        ports:
            - "3309:3306"
        volumes:
            - vprofile-db-data:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=accounts"
            - "MYSQL_ROOT_PASSWORD=vprodbpass"
        networks:
            - vprofile-networks

    vprofile-cache:
        image: memcached
        container_name: vprocache01
        ports:
          - "11211:11211"
        networks:
            - vprofile-networks
    
    vprofile-rabbitmq:
        image: rabbitmq
        container_name: vpromq01
        ports:
            - "5672:5672"
        environment:
            - "RABBITMQ_DEFAULT_USER=guest" 
            - "RABBITMQ_DEFAULT_PASS=guest"
        networks:
            - vprofile-networks

    vprofile-app:
        build:
            context: .
            dockerfile: ./app/Dockerfile
        container_name: vprofile
        image: sramtekkar/vprofile-app
        ports:
            - "8080:8080"
        volumes:
          - vprofile-app-data:/usr/local/tomcat/webapps
        networks:
            - vprofile-networks
    
    vprofile-nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: vprofile-nginx
        image: sramtekkar/vprofile-nginx
        ports:
            - "80:80"
        depends_on:
            - vprofile-app
        networks:
            - vprofile-networks
        restart: always
    


    