
Vagrant.configure("2") do |config|
   config.hostmanager.enable = true
   config.hostmanager.manage_host = true


   config.vm.define "mongo" do |mongo|
      mongo.vm.box = "ubuntu/jammy64"
      mongo.vm.hostname = "mongo"
      mongo.vm.network "private_network", ip: "192.168.57.10"
      mongo.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.cpus = 2
      end
      mongo.vm.provision "shell", path: "./mongodb.sh"
   end

   config.vm.define "jenkins" do |jenkins|
      jenkins.vm.box = "ubuntu/jammy64"
      jenkins.vm.hostname = "jenkins"
      jenkins.vm.network "private_network", ip: "192.168.57.11"
      jenkins.vm.provider "virtualbox" do |vb|
         vb.memory = "4096"
         vb.cpus = 2
      end
      jenkins.vm.provision "shell", path: "./jenkins.sh"
   end

   config.vm.define "sonarqube" do |sonarqube|
      sonarqube.vm.box = "ubuntu/jammy64"
      sonarqube.vm.hostname = "sonarqube"
      sonarqube.vm.network "private_network", ip: "192.168.57.12"
      sonarqube.vm.provider "virtualbox" do |vb|
         vb.memory = "4096"
         vb.cpus = 2
      end
      sonarqube.vm.provision "shell", path: "./sonarqube.sh"
   end

   config.vm.define "nexus" do |nexus|
      nexus.vm.box = "ubuntu/jammy64"
      nexus.vm.hostname = "nexus"
      nexus.vm.network "private_network", ip: "192.168.57.13"
      nexus.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.cpus = 2
      end
      nexus.vm.provision "shell", path: "./nexus.sh"
   end
 
end
